# Generated by Django 5.2.2 on 2025-06-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='profile_pics/default-user.png', upload_to='profile_pics/'),
        ),
    ]
